server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
  auto_run: true
data:
  database:
    driver: sqlite
    source: ./bin/demo1kratos.db
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
